credentials-file: /etc/cloudflared/92d8df83-3623-4850-ba41-29126106d020.json
ingress:
  - hostname: dev.setrox.com.tr
    service: http://127.0.0.1:8090
  - hostname: grafana.setrox.com.tr
    service: http://127.0.0.1:3002
  - hostname: status.setrox.com.tr
    service: http://127.0.0.1:3001
  - hostname: n8n.setrox.com.tr
    service: http://127.0.0.1:5678
  - hostname: code.setrox.com.tr
    service: http://127.0.0.1:8444
  - hostname: pdf.setrox.com.tr
    service: http://127.0.0.1:8080
  - hostname: db.setrox.com.tr
    service: http://127.0.0.1:5050
  - hostname: dash.setrox.com.tr
    service: http://127.0.0.1:18789
  - hostname: coder.setrox.com.tr
    service: http://127.0.0.1:7080
  - hostname: restmenu.setrox.com.tr
    service: http://127.0.0.1:3501
  - hostname: antfarm.setrox.com.tr
    service: http://127.0.0.1:3333
  - hostname: ai.setrox.com.tr
    service: http://127.0.0.1:3080
  - hostname: expense-tracker.setrox.com.tr
    service: http://127.0.0.1:3513
  - hostname: snippetbox.setrox.com.tr
    service: http://127.0.0.1:3521
  - hostname: aitoolpeak.setrox.com.tr
    service: http://127.0.0.1:3525
  - service: http_status:404
tunnel: 92d8df83-3623-4850-ba41-29126106d020
